Teste.EL.Site/Teste.EL.Site.Web/Controllers/ListagemAluguelController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Teste.EL.Site.Business.BLL;
using Teste.EL.Site.DataTransferObjects.DTO;
using Teste.EL.Site.Entidades.DTO;
using Teste.EL.Site.Entidades.Enum;
using Teste.EL.Site.Web.Models;

namespace Teste.EL.Site.Web.Controllers
{
    public class ListagemAluguelController : BaseController
    {
        private readonly ReservaBusiness _reservaBusiness;

        public ListagemAluguelController() 
        {
            _reservaBusiness = new ReservaBusiness();
        }

        public IActionResult Index()
        {
            List<AluguelDTO> listaAlugueisCliente = new List<AluguelDTO>();
            var cliente = ObterClienteLogado();

            if (cliente != null)
                listaAlugueisCliente = ListarAluguelPorCliente(cliente.IdCliente);

            base.PreencherViewBagUsuarioLogado();
            return View(new ListagemAluguelModel(listaAlugueisCliente));
        }

        public IActionResult FeedBack()
        {
            base.PreencherViewBagUsuarioLogado();
            return View();
        }
        public IActionResult AgradecimentoFeedback()
        {
            base.PreencherViewBagUsuarioLogado();
            return View();
        }

        public PartialViewResult ListarPorPeriodo([FromQuery] DateTime? periodoInicio, DateTime? periodoFinal)
        {
            List<AluguelDTO> listaAlugueisCliente = new List<AluguelDTO>();
            var cliente = ObterClienteLogado();

            if (cliente != null)
                listaAlugueisCliente = ListarAluguelPorCliente(cliente.IdCliente);

            if (periodoInicio.HasValue)
                listaAlugueisCliente.RemoveAll(aluguel => aluguel.DataPrevistaAluguel < periodoInicio.Value);

            if (periodoFinal.HasValue)
                listaAlugueisCliente.RemoveAll(aluguel => aluguel.DataPrevistaAluguel > periodoFinal.Value);

            return PartialView("~/Views/ListagemAluguel/_GridAlugueis.cshtml", new ListagemAluguelModel(listaAlugueisCliente));
        }

        private List<AluguelDTO> ListarAluguelPorCliente(int idCliente)
        {
            return _reservaBusiness.ListarPorIdCliente(idCliente, ObterJWToken());
        }
    }
}

Teste.EL.Site/Teste.EL.Site.Web/Views/ListagemAluguel/AgradecimentoFeedback.cshtml
<h1>Agradecemos pelo Feedback!</h1>
<h3>Sua opinião é muito importante para nos ajudar a melhorar nosso atendimento.</h3>

<div>
    <a asp-action="Index" asp-controller="Home"> Quer dar uma olhada em outros automóveis? Clique Aqui.</a>
</div>

Teste.EL.Site/Teste.EL.Site.Web/Views/ListagemAluguel/Feedback.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
<!--  ----------------------------------------------------------------------  -->
<!--  NOTE: Please add the following <META> element to your page <HEAD>.      -->
<!--  If necessary, please modify the charset parameter to specify the        -->
<!--  character set of your HTML page.                                        -->
<!--  ----------------------------------------------------------------------  -->

<META HTTP-EQUIV="Content-type" CONTENT="text/html; charset=UTF-8">

<!--  ----------------------------------------------------------------------  -->
<!--  NOTE: Please add the following <FORM> element to your page.             -->
<!--  ----------------------------------------------------------------------  -->




<div id="formulario-feedback">
    <center>
        <div class="row">
            <div class="col-md-12 section-header" style="border-bottom: 1px solid; border-bottom-color: #eaeaea; padding-bottom:10px;">
                <h3 class="title">
                    FOMULÁRIO DE FEEDBACK DO ALUGUEL
                </h3>
            </div>
        </div>
        <br />
        <center>
            <div class="row">
                <div class="col-md-12">
                    <div class="row">
                        <div class="col-md-12">
                            <form id="feedback-salesforce" action="https://webto.salesforce.com/servlet/servlet.WebToCase?encoding=UTF-8" method="POST">

                                <input type=hidden name="orgid" value="00D4x000007JnaY">
                                <input type=hidden name="retURL" value="http://">
                                <div class="form-group">
                                    <label for="name">Nome do Contato</label>
                                    <div class="col-md-4">
                                        <input id="name" class="form-control" maxlength="80" name="name" size="20" type="text" />
                                    </div>
                                </div>
                                <div class="form-group">
                                    <label for="name">E-mail</label>
                                    <div class="col-md-4">
                                        <input id="email" class="form-control" maxlength="80" name="email" size="20" type="text" />
                                    </div>
                                </div>
                                <div class="form-group">
                                    <label for="name">Telefone</label>
                                    <div class="col-md-4">
                                        <input id="phone" class="form-control" maxlength="80" name="phone" size="20" type="text" />
                                    </div>
                                </div>
                                <div class="form-group">
                                    <label for="name">Assunto</label>
                                    <div class="col-md-4">
                                        <input id="subject" class="form-control" maxlength="80" name="subject" size="20" type="text" />
                                    </div>
                                </div>
                                <div class="form-group">
                                    <label for="name">Descrição do Feedback</label>
                                    <div class="col-md-4">
                                        <textarea name="description" class="form-control"></textarea>
                                    </div>
                                </div>
                                <div class="form-group">
                                    <div class="col-md-offset-9 col-md-2">
                                        <button type="button" class="btn btn-success" onclick="aoClicarEmSubmeterFeedback();"> Enviar</button>
                                    </div>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </center>
    </center>
</div>

<script>
    var URL_PAGINA_AGRADECIMENTO = '@Url.Action("AgradecimentoFeedback")';

    function aoClicarEmSubmeterFeedback() {
        var form = $("#feedback-salesforce");
        var actionURL = form.attr("action");
        $.ajax({
            url: actionURL,
            data: form.serialize(),
            cache: false,
            success: function (result) {
                window.location.href = URL_PAGINA_AGRADECIMENTO;
            },
            error: function () {
                window.location.href = URL_PAGINA_AGRADECIMENTO;
            }
        });
    }
</script>

Teste.EL.Site/Teste.EL.Site.Web/Views/ListagemAluguel/Index.cshtml
@model ListagemAluguelModel

@{
    ViewData["Title"] = "View";
}

<div id="filtro-listagem-veiculo">
    <div class="row">
        <div class="col-md-12 section-header" style="text-align: left; border-bottom: 1px solid; border-bottom-color: #eaeaea; padding-bottom:10px;">
            <h3 class="title">
                Listagem de Alugueis
            </h3>
        </div>
    </div>
</div>
<br />
<br />

<div class="row">
    <div class="form-group">
        <div class="row">
            <div class="col-md-6">
                <div class="row">
                    <div class="col-md-4" style="vertical-align: middle; text-align: right;">
                        <label asp-for="PeriodoInicio" class="control-label">Período Início</label>
                    </div>
                    <div class="col-md-7">
                        <input asp-for="PeriodoInicio" class="form-control" />
                    </div>
                </div>
            </div>
            <div class="col-md-5">
                <div class="row">
                    <div class="col-md-4" style="vertical-align: middle; text-align: right;">
                        <label asp-for="PeriodoFinal" class="control-label">Período Fim</label>
                    </div>
                    <div class="col-md-8">
                        <input asp-for="PeriodoFinal" class="form-control" />
                    </div>
                </div>
            </div>
            <div class="col-md-1">
                <div class="row">
                    <div class="col-md-12">
                        <div class="col-md-6"></div>
                        <div class="col-md-6">
                            <center>
                                <button href="#" id="filtro-data" class="btn btn-success" onclick="aoClicarEmFiltrar();">
                                    <span class="glyphicon glyphicon-star-empty">Filtrar</span>
                                </button>
                            </center>
                        </div>
                    </div>
                </div>
            </div>
        </div>

    </div>
</div>
<br />
<br />

<div id="grid-listagem-luguel">
    @Html.Partial("_GridAlugueis", Model)
</div>

<script>
    var URL_FILTRO_DATA = '@Url.Action("ListarPorPeriodo", "ListagemAluguel")';

    function aoClicarEmFiltrar() {
        var data = {
            periodoInicio: $('#PeriodoInicio').val(),
            periodoFinal: $('#PeriodoFinal').val()
        }
        chamadaGET(URL_FILTRO_DATA, data, ListarPorPeriodoSucesso);
    }

    function ListarPorPeriodoSucesso(data) {
        if (data) {
            $('#grid-listagem-luguel').html(data);
            $('#grid-listagem-luguel').load();
        }
    }
</script>

Teste.EL.Site/Teste.EL.Site.Web/Views/ListagemAluguel/_GridAlugueis.cshtml
@model ListagemAluguelModel

<table class="table">
    <thead>
        <tr>
            <th>
                Código Aluguel
            </th>
            <th>
                Categoria
            </th>
            <th>
                Data Aluguel
            </th>
            <th>
                Placa
            </th>
            <th>
                Valor/Hora
            </th>
            <th>
                Total Horas
            </th>
            <th>
                Valor Final
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model.ListaAluguelCliente)
        {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.IdAluguel)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Categoria)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.DataPrevistaAluguel)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Placa)
            </td>
            <td>
                @String.Format(new System.Globalization.CultureInfo("pt-BR"), "{0:C}", item.ValorHora)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.TotalDeHoras)
            </td>
            <td>
                @String.Format(new System.Globalization.CultureInfo("pt-BR"), "{0:C}", item.ValorFinalAluguel)
            </td>
            <td>
                @Html.ActionLink("Dar Feedback!", "Feedback")
            </td>
        </tr>
        }
    </tbody>
</table>